name: 'Setup Omnistrate CTL'
description:
  'Wraps the Omnistrate CTL command line to deploy and operate Omnistrate
  services'
author: 'Omnistrate'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'command'
  color: 'green'

# Define your inputs here.
inputs:
  email:
    description: 'User email'
    required: false
  password:
    description: 'User password'
    required: false
  version:
    description: 'Omnistrate CTL version'
    required: false

runs:
  using: node20
  main: dist/install/index.js
  post: dist/post/index.js
