name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./

      - name: Test Local Action CTL
        run: |
          omnistrate-ctl --version
          omctl --help

  test-action-with-version:
    name: GitHub Actions Test with Version

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action with Version
        id: test-action-with-latest
        uses: ./
        with:
          version: v0.9.34

      - name: Test Local Action CTL
        run: |
          omnistrate-ctl --version
          omctl --help

  test-action-with-email-and-password:
    name: GitHub Actions Test with Email and Password

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action with Email and Password
        id: test-action-with-email-and-password
        uses: ./
        with:
          email: ${{ secrets.OMNISTRATE_ACCOUNT_EMAIL }}
          password: '${{ secrets.OMNISTRATE_ACCOUNT_PASSWORD }}'

      - name: Test Local Action CTL
        run: |
          omnistrate-ctl --version
          omctl --help

      - name: List Local Action CTL
        run: omctl list
